version: "3.8"
services:
  db:
    image: postgres:17  # Используем стабильную версию
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./data:/var/lib/postgresql/data  # Используем том для хранения данных
      - ./lexa_dump.sql:/docker-entrypoint-initdb.d/lexa_dump.sql  # Дамп базы данных
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 10s
      retries: 10
    networks:
      - lexa_network

  bot:
    build: .
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    networks:
      - lexa_network

networks:
  lexa_network:
    driver: bridge
